# Generated by Django 5.2.14 on 2026-05-27 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0002_alter_author_id_alter_book_id_alter_comment_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('камера', 'Камера'), ('спектрометр', 'Спектрометр'), ('магнитометр', 'Магнитометр'), ('радар', 'Радар'), ('плазменный анализатор', 'Плазменный анализатор')], max_length=25)),
                ('mass_kg', models.DecimalField(decimal_places=2, max_digits=8)),
                ('power_consumption_w', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission_name', models.CharField(max_length=100, unique=True)),
                ('budget_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('планируется', 'Планируется'), ('активна', 'Активна'), ('завершена', 'Завершена'), ('неудача', 'Неудача')], default='планируется', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Spacecraft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('country', models.CharField(max_length=50)),
                ('launch_date', models.DateField()),
                ('power_watts', models.PositiveIntegerField()),
                ('mass_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('проектируется', 'Проектируется'), ('в пути', 'В пути'), ('на орбите Юпитера', 'На орбите Юпитера'), ('завершена', 'Завершена'), ('авария', 'Авария')], default='проектируется', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('type', models.CharField(choices=[('галилеевы', 'Галилеевы'), ('регулярные', 'Регулярные'), ('иррегулярные', 'Иррегулярные')], max_length=20)),
                ('diameter_km', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('gravity_ms2', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('has_ocean', models.BooleanField(default=False)),
                ('notable_feature', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.RemoveField(
            model_name='book',
            name='genres',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='book',
        ),
        migrations.CreateModel(
            name='MissionInstrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('commissioning_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api_v1.instrument')),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_v1.mission')),
            ],
            options={
                'unique_together': {('mission', 'instrument')},
            },
        ),
        migrations.AddField(
            model_name='mission',
            name='spacecraft',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api_v1.spacecraft'),
        ),
        migrations.AddField(
            model_name='mission',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api_v1.target'),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
